#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Publish the qBittorrent WebUI through the node Traefik instance.
#

import json
import os
import sys

import agent
import agent.tasks
import qbittorrent

data = json.load(sys.stdin)

host = data.get("host")
h2hs = data.get("http2https", True)
le = data.get("lets_encrypt", False)

qbittorrent.set_many({
    "TRAEFIK_HOST": host,
    "TRAEFIK_HTTP2HTTPS": h2hs,
    "TRAEFIK_LETS_ENCRYPT": le,
})

# Find the default Traefik instance for the current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url': 'http://127.0.0.1:' + os.environ['TCP_PORT'],
        'host': host,
        'http2https': h2hs,
        'lets_encrypt': le,
    },
)

# Check if traefik configuration has been successful
agent.assert_exp(response['exit_code'] == 0)
