#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Store the default settings, so that the Systemd units have everything
# they need even before configure-module runs for the first time.
#

import qbittorrent

qbittorrent.set_many(qbittorrent.settings_env({}))
